### ISSUE TITLE
Not sending via UDP to loxone

### ISSUE THREAD

**Issue by KrisDeCaluwe** [sunsus/LoxBerry-Plugin-EcoWater#1]
Hi,

The application is not forwarding the information to loxone and I do get the following apache (see error.1.log file) the other file is the log file from the 
[error (1).log](https://github.com/sunsus/LoxBerry-Plugin-EcoWater/files/4193580/error.1.log)
[20200212_173202_269_request.log](https://github.com/sunsus/LoxBerry-Plugin-EcoWater/files/4193552/20200212_173202_269_request.log)
Do you happen to know what can be done to resolve the issue?

Thanks in advance 
Kris

**Comment by sunsus** [comment]
Hi Kris 

The log looks good, have you configured you minisever in the LoxBerry? Does any other UDP Communication works? 

regeards

Patrick

**Comment by KrisDeCaluwe** [comment]
After today's update of the application the udp started working as it should.Thanks alot!
